config/routes.rb
Rails.application.routes.draw do
  root 'prompt_templates#index'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :prompt_templates
  resources :categories

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :prompt_templates
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, presence: true, uniqueness: true 
end

app/models/category_prompt_template.rb
class CategoryPromptTemplate < ApplicationRecord
  belongs_to :category
  belongs_to :prompt_template

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prompt_template

  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
  validates :prompt_template_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :prompt_template

  validates :user_id, presence: true
  validates :prompt_template_id, presence: true
end

app/models/prompt_template.rb
class PromptTemplate < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user, optional: true
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  validates :category_id, presence: true
end

app/models/save_prompt.rb
class SavePrompt < ApplicationRecord
  belongs_to :user
  belongs_to :prompt_template
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password_confirmation

  has_many :prompt_templates
  has_many :likes
  has_many :comments

  # validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/prompt_templates_controller.rb
class PromptTemplatesController < ApplicationController
  def index
    @prompt_templates = PromptTemplate.all
    @categories = Category.all
  end
  
  def new
    @prompt_template = PromptTemplate.new
  end
  
  def create
    @prompt_template = current_user.prompt_templates.build(prompt_template_params)
  
    if @prompt_template.save
      redirect_to @prompt_template, notice: 'Prompt template was successfully created.'
    else
      render :new
    end
  end
  
  def show
    @prompt_template = PromptTemplate.find(params[:id])
  end
  
  def edit
    @prompt_template = PromptTemplate.find(params[:id])
  end
  
  def update
    @prompt_template = PromptTemplate.find(params[:id])
  
    if @prompt_template.update(prompt_template_params)
      redirect_to prompt_templates_path, notice: 'Prompt template was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @prompt_template = PromptTemplate.find(params[:id])
    @prompt_template.likes.destroy_all
    @prompt_template.comments.destroy_all
    @prompt_template.destroy
  
    redirect_to prompt_templates_path, notice: 'Prompt template was successfully deleted.'
  end
  
  private
  
  def prompt_template_params
    params.require(:prompt_template).permit(:title, :content, :category_id)
  end  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'ログインに成功しました')
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :show, :edit, :update, :destroy]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def require_login
    unless current_user
      flash[:error] = "ログインが必要です。"
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/prompt_templates_helper.rb
module PromptTemplatesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_categories_list.html.erb
<%# app/views/categories/_categories_list.html.erb %>

<h2 data-v-0ada92f4="" data-v-0e51b078="" class="mb-4">Categories</h2>


<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

  <% categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <%= link_to 'Edit', edit_category_path(category) %> |
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Category', new_category_path %>

app/views/categories/_form.html.erb
# app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
# app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= render 'categories/form', category: Category.new %>

app/views/categories/new.html.erb
# app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
# app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/prompt_templates/_form.html.erb
<%= form_with model: prompt_template, local: true do |form| %>
  <% if prompt_template.errors.any? %>
    <div>
      <h2><%= pluralize(prompt_template.errors.count, "error") %> prohibited this prompt_template from being saved:</h2>
      <ul>
        <% prompt_template.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect { |c| [c.name, c.id] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prompt_templates/edit.html.erb
<h1>Edit Prompt Template</h1>

<%= render 'form', prompt_template: @prompt_template %>

<%= link_to 'Back', prompt_templates_path %>

app/views/prompt_templates/index.html.erb
<%# app/views/prompt_templates/index.erb %>
<h1>Prompt Templates</h1>


<%= render 'categories/categories_list', categories: @categories %>

<%= link_to 'New Prompt Template', new_prompt_template_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Actions</th>
  </tr>

  <% @prompt_templates.each do |prompt_template| %>
    <tr>
      <td><%= prompt_template.title %></td>
      <td><%= prompt_template.content %></td>
      <td>
        <%= link_to 'Edit', edit_prompt_template_path(prompt_template) %> |
        <%= form_with url: prompt_template_path(prompt_template), method: :delete, local: true, class: "d-inline" do %>
          <%= submit_tag 'Delete', data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/prompt_templates/new.html.erb
<h1>New Prompt Template</h1>

<%= render 'form', prompt_template: @prompt_template %>

<%= link_to 'Back', prompt_templates_path %>

app/views/prompt_templates/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @prompt_template.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @prompt_template.content %>
</p>

app/views/user_sessions/new.html.erb
<!-- ビューファイル -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ログインページ</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
  #intro {
    background-image: url('/packs/media/images/ancient_library.png');
    height: 100vh;
   }
   /* 他のスタイル */
  </style>
</head>
<body>
  <div id="intro" class="bg-image shadow-2-strong">
    <div class="mask d-flex align-items-center h-100" style="background-color: rgba(0, 0, 0, 0.8);">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-5 col-md-8">
            <form class="bg-white rounded-form shadow-5-strong p-5">
              <!-- Email input -->
              <div class="form-outline mb-4">
                <input type="email" id="form1Example1" class="form-control" />
                <label class="form-label" for="form1Example1">Email address</label>
              </div>

              <!-- Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="form1Example2" class="form-control" />
                <label class="form-label" for="form1Example2">Password</label>
              </div>

              <!-- 2 column grid layout for inline styling -->
              <div class="row mb-4">
                <div class="col d-flex justify-content-center">
                  <!-- Checkbox -->
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
                    <label class="form-check-label" for="form1Example3">
                      Remember me
                    </label>
                  </div>
                </div>

                <div class="col text-center">
                  <!-- Simple link -->
                  <a href="#!">Forgot password?</a>
                </div>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block">Sign in</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>件のエラーが発生しました:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "更新" %>
  </div>
<% end %>

<%= link_to "戻る", user_path(@user) %>

app/views/users/new.html.erb
<h1>新規ユーザー登録</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>件のエラーが発生しました:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to "編集", edit_user_path(@user) %> |
<%= link_to "削除", user_path(@user), method: :delete, data: { confirm: "本当に削除しますか？" } %> |
<%= link_to "戻る", root_path %>